-- =============================================================================
-- billing_audit_events: add correlation_id
-- =============================================================================
-- correlation_id links related billing audit events emitted by a single atomic
-- operation (void+reissue, issue_and_pay, bulk payment parent+children) so the
-- audit drawer can group them. Nullable: existing rows and standalone events
-- carry NULL and render independently. UUID v7 is generated by the application
-- (time-ordered) so sorting by id approximates chronological order.
-- =============================================================================

ALTER TABLE public.billing_audit_events
  ADD COLUMN IF NOT EXISTS correlation_id uuid;

-- Group lookup scoped to a period (index-safe for the audit list correlation filter)
CREATE INDEX IF NOT EXISTS idx_billing_audit_events_period_correlation
  ON public.billing_audit_events (billing_period_id, correlation_id)
  WHERE correlation_id IS NOT NULL;
